### ISSUE TITLE
Vagrant doesn't support version 6.1 of VirtualBox

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/sample-app-web#21]
I attempted to follow the installation steps and got the following error message. It looks as if the current VirtualBox version of 6.1 isn't supported by Vagrant.

> The provider 'virtualbox' that was requested to back the machine
> 'default' is reporting that it isn't usable on this system. The
> reason is shown below:
> 
> Vagrant has detected that you have a version of VirtualBox installed
> that is not supported by this version of Vagrant. Please install one of
> the supported versions listed below to use Vagrant:
> 
> 4.0, 4.1, 4.2, 4.3, 5.0, 5.1, 5.2, 6.0
> 
> A Vagrant update may also be available that adds support for the version
> you specified. Please check www.vagrantup.com/downloads.html to download
> the latest version.

**Comment by wswebcreation** [comment]
Vagrant needs to be removed in the future and a plain local version for testing with WebdriverIO needs to be used.

**Comment by nadvolod** [comment]
Any idea when that's going to happen? I wasn't able to get this app to work locally

**Comment by wswebcreation** [comment]
I'll take a look at it this or next week and create a PR for it

**Comment by wswebcreation** [comment]
@nadvolod 

Already started with the work, see https://github.com/saucelabs/sample-app-web/tree/chore/remove-vagrant

I only need to fix the tests and then I can make a PR. Hope to be able to fix that before my PTO

**Comment by nadvolod** [comment]
Hello everyone. Any update on this? It would be nice to be able to build this app locally so that we can demo Sauce Labs solutions to clients?
Otherwise, I'd have to create my own sample app so that I can demo it to clients. Which I can do, but it would be nice if we have consistency across Sauce.
