### ISSUE TITLE
Add CI to the project

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/sample-app-web#24]
I think that it would be nice to have this running through CI so that we can automatically validate that the code is working. I'm happy to help

**Comment by wswebcreation** [comment]
Good 💡

You can do that when the new build approach has been merged.

**Comment by wswebcreation** [comment]
@nadvolod 

@richard-sl added GitHub actions for at least the deployment of the app, we can add the tests there later, see https://github.com/saucelabs/sample-app-web/pull/33

**Comment by wswebcreation** [comment]
Closing for now
