### ISSUE TITLE
[Feature] Is it possible to add data-test to more elements?

### ISSUE THREAD

**Issue by ltsuda** [saucelabs/sample-app-web#92]
Hi guys,

thanks for this project and for the new updated design. As the title says, is it possible, when possible, for you guys to add `data-test` to more elements? Like inventory containers, items, menu/sidebar and item detail card, etc.?

I forked this project in 2021 to study Playwright and I ended up adding some of these on my own but as I'm not a frontend developer, it's possible that I didn't follow best practices where I added those tags.

I would love to update my study repository to use the new design and update the Playwright Test I used so I can add the newest features.

Thanks again ❤️

**Comment by diemol** [comment]
Yes, please send a PR to the element you'd like and we can merge it.

**Comment by ltsuda** [comment]
Cool! I will review my changes again this week and open a PR. Just note that this is not critical as I forked this project and to study in general, data-test is not required at all :)
